### ISSUE TITLE
Does the demo work?

### ISSUE THREAD

**Issue by mandelmonkey** [qurihara/picognizer#1]
Hi

I tried the demo on chrome but it doesn't seem to detect the coin sound
I can see this error in the console

```
4picognizer_browser.js:1515 Uncaught TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at average (picognizer_browser.js:1515:12)
    at picognizer_browser.js:1436:11
average @ picognizer_browser.js:1515
(anonymous) @ picognizer_browser.js:1436
setInterval (async)
costCalculation @ picognizer_browser.js:1434
func @ picognizer_browser.js:1209
Code.execfuncs @ picognizer_browser.js:106
(anonymous) @ picognizer_browser.js:1274
/picognizer/[object%20MediaStream]:1          GET https://qurihara.github.io/picognizer/[object%20MediaStream] net::ERR_ABORTED 404

```

**Comment by mandelmonkey** [comment]
I can see you said it works best with firefox so closing
